"""
Communication / Learning / Questioning curriculum — TEACHER-GENERATED and LIVE.

Nothing here is a hardcoded training seed. The only authored content is the list
of SKILL AREAS to teach (your directive: communication, learning, questioning)
and a short description of each. Every actual practice seed is GENERATED by the
local teacher model, and the curriculum is kept live:

  (a) a fresh batch is generated at each /auto start,
  (b) new batches are generated continuously while it runs (growth),
  (c) everything is merged into a persistent cache so nothing is ever lost.

So the local models are always authoring new material as they teach.
"""
import os
import json
import re

from omni.logging_config import get_logger

logger = get_logger("OmniCurriculum", "curriculum.log")

_CACHE_PATH = os.path.join(os.path.dirname(__file__), "curricula_generated.json")

# The only authored content: WHAT to teach (your requirement). The teacher
# generates every actual practice prompt from these descriptions.
SKILL_AREAS = {
    "communication": (
        "holding a warm, natural, human conversation — greetings and small talk, "
        "matching tone and energy, empathy, expressing honest opinions and "
        "personality, humour, disagreeing kindly, and keeping a conversation going"
    ),
    "learning": (
        "meta-cognition and learning skills — honestly admitting when it does not "
        "know something, restating an explanation in its own words to confirm it "
        "understood, correcting itself gracefully, and building on things it has "
        "just been taught"
    ),
    "questioning": (
        "asking good questions — when it is unsure or confused, asking ONE specific, "
        "curious clarifying question RELATED to exactly what confused it, instead of "
        "guessing or babbling; also asking natural follow-up questions to learn more"
    ),
}


# Degenerate/placeholder patterns that must never enter the live curriculum
# (e.g. stub-test output like "Scenario 7-0: respond naturally to this situation
# number 0."). Guards the persistent cache against templated junk.
_PLACEHOLDER = re.compile(
    r'(?i)respond naturally to this situation number|'
    r'\bscenario\s+\d+\s*[-.]\s*\d+|'
    r'\bsituation\s+number\s+\d+'
)


def _looks_placeholder(seed):
    return bool(_PLACEHOLDER.search(seed))


def _parse_seeds(raw_text):
    """Turn a teacher's free-text list into clean individual seed prompts."""
    seeds = []
    for line in raw_text.splitlines():
        line = line.strip()
        if not line:
            continue
        line = re.sub(r'^\s*(?:\d+[.)]|[-*•])\s*', '', line).strip()   # strip numbering/bullets
        if len(line) >= 2 and line[0] in '"“' and line[-1] in '"”':
            line = line[1:-1].strip()
        if len(line) >= 12 and not _looks_placeholder(line):
            seeds.append(line)
    return seeds


def generate_seeds(teacher, areas=None, n_per_area=40):
    """Generate a FRESH batch of teacher-authored seeds for the given areas."""
    areas = areas or list(SKILL_AREAS)
    system = (
        "You are an expert curriculum designer for an infant conversational AI that "
        "learns by absorbing example conversations. You produce concise, varied "
        "PRACTICE PROMPTS — each a short, realistic scenario asking for a natural "
        "response that demonstrates a specific skill. Output ONLY the prompts, one "
        "per line, with no numbering, headers, or commentary."
    )
    out = {}
    for area in areas:
        desc = SKILL_AREAS[area]
        prompt = (
            f"Generate {n_per_area} diverse practice prompts that teach an infant "
            f"conversational AI this skill: {desc}.\n\n"
            f"Vary the scenarios as widely as you can — different topics, wordings, "
            f"moods, and situations. Each prompt stands alone and asks for a short, "
            f"natural response. One prompt per line, nothing else."
        )
        raw = teacher.generate_raw(prompt, system=system, num_predict=4096)
        out[area] = _parse_seeds(raw)
        logger.info(f"Generated {len(out[area])} fresh seeds for '{area}'")
    return out


def load_cache(cache_path=_CACHE_PATH):
    if os.path.exists(cache_path):
        try:
            with open(cache_path) as f:
                raw = json.load(f)
            # Drop any placeholder/templated junk that may already be cached.
            return {area: [s for s in seeds if not _looks_placeholder(s)]
                    for area, seeds in raw.items()}
        except Exception as e:
            logger.warning(f"Could not read curricula cache: {e}")
    return {}


def save_cache(curricula, cache_path=_CACHE_PATH):
    try:
        with open(cache_path, "w") as f:
            json.dump(curricula, f, indent=2)
    except Exception as e:
        logger.error(f"Could not persist curricula cache: {e}")


def _merge(base, fresh):
    """Append fresh seeds onto base per area, de-duplicating, preserving order."""
    out = {area: list(base.get(area, [])) for area in SKILL_AREAS}
    for area, seeds in fresh.items():
        seen = set(out.get(area, []))
        for s in seeds:
            if s not in seen:
                out.setdefault(area, []).append(s)
                seen.add(s)
    return out


def refresh_curricula(teacher, areas=None, n_per_area=40, cache_path=_CACHE_PATH):
    """
    Generate a fresh batch and MERGE it into the persistent cache, then return the
    merged curriculum. This single call delivers all three behaviours:
      * fresh generation now (regenerate),
      * merged onto everything generated before (grow),
      * persisted so it is never lost (cache).
    Call it at /auto start (all areas) and periodically during the loop (one area).
    """
    base = load_cache(cache_path)
    fresh = generate_seeds(teacher, areas=areas, n_per_area=n_per_area)
    merged = _merge(base, fresh)
    save_cache(merged, cache_path)
    total = sum(len(v) for v in merged.values())
    logger.info(f"Curriculum refreshed (areas={areas or 'all'}); now {total} seeds total")
    return merged


if __name__ == "__main__":
    from omni.teacher_scaffold import LocalTeacher
    t = LocalTeacher()
    c = refresh_curricula(t, n_per_area=6)
    for area, seeds in c.items():
        print(f"{area:14} {len(seeds):3} seeds  e.g. {seeds[0][:70]!r}")
