"""
DistillationEngine — Multi-model knowledge distillation into Unison's
zero-parameter SynapticGraph.

Rotates through every available local model, each with its own tailored
curriculum. Detects stagnation (repetitive answers) and auto-switches
to the next model. The Observer Teacher monitors quality throughout.

Supported model sources:
- Ollama (models already loaded)
- GGUF files on external SSD (loaded via llama-server on demand)

512GB M3 Ultra: all models fit — even the largest run one at a time.
"""
import os
import json
import time
import hashlib
import subprocess
import signal
import requests
from collections import deque
from omni.logging_config import get_logger

distill_logger = get_logger("OmniDistill", "distill.log")

# ── External SSD paths ──
_SSD_BASE = "/Volumes/One Touch/models library"
_GGUF_DIR = f"{_SSD_BASE}/GGUF_Models"
_HIST_DIR = f"{_SSD_BASE}/Historical_Models"

# ═══════════════════════════════════════════════════════════════════════════
# CURRICULA — One per model class, rotated through during distillation
# ═══════════════════════════════════════════════════════════════════════════
from omni.curriculum_communication import refresh_curricula, load_cache, SKILL_AREAS
from omni.teacher_scaffold import detect_context_window

# How often (in /auto iterations) to generate & merge a fresh batch of seeds for
# one rotating skill area — the "continuous growth" of the live curriculum.
CURRICULUM_GROW_EVERY = 15

import glob
import os

def _build_sft_curricula():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    constants_dir = os.path.join(base_dir, "constants")
    
    sft_sm_qft = []
    sft_cosmology = []
    sft_biochem = []
    sft_classical_condensed = []
    
    if os.path.isdir(constants_dir):
        for f in os.listdir(constants_dir):
            if not f.endswith(".ep"): continue
            file_path = os.path.join(constants_dir, f)
            name = f.replace(".ep", "").replace("_", " ")
            
            # Read actual content to prevent hallucination
            try:
                with open(file_path, "r", encoding="utf-8") as f_obj:
                    content = f_obj.read()
            except Exception as e:
                continue
                
            prompt = f"Teach Unison about the SFT concept of '{name}' using the following text as your absolute ground truth. Explain it clearly and conversationally, but strictly adhere to this text without hallucinating:\n\n{content}"
            
            # Simple keyword routing
            if any(k in name for k in ["quark", "lepton", "boson", "mass", "neutrino", "strong", "weak", "yang", "cp"]):
                sft_sm_qft.append(prompt)
            elif any(k in name for k in ["cosmo", "black hole", "hubble", "inflation", "baryon", "dark"]):
                sft_cosmology.append(prompt)
            elif any(k in name for k in ["bio", "chem", "protein", "life", "genetic", "periodic", "acid"]):
                sft_biochem.append(prompt)
            else:
                sft_classical_condensed.append(prompt)
    
    # Fallbacks if constants dir is missing/empty
    if not sft_sm_qft: sft_sm_qft = ["Explain the SFT derivation for fine structure constant."]
    if not sft_cosmology: sft_cosmology = ["Explain the SFT derivation for cosmological constant."]
    if not sft_biochem: sft_biochem = ["Explain the SFT derivation for genetic code."]
    if not sft_classical_condensed: sft_classical_condensed = ["Explain the SFT derivation for newton law."]

    return sft_sm_qft, sft_cosmology, sft_biochem, sft_classical_condensed

CURRICULUM_SM_QFT, CURRICULUM_COSMOLOGY, CURRICULUM_BIOCHEM, CURRICULUM_CLASSICAL = _build_sft_curricula()

CURRICULUM_TOOL_USE = [
    "[TOOL_USE] Please use internet_access to look up the current news.",
    "[TOOL_USE] Use your scratch_pad to store the value '137' under the key 'alpha'.",
    "[TOOL_USE] What is the current time_and_date?",
    "[TOOL_USE] Use read_own_code to read omni/distill.py.",
    "[TOOL_USE] Use read_logs to check the latest voice.log errors.",
]

# Map curriculum names to their seed lists
CURRICULA = {
    # communication / learning / questioning are injected at engine start,
    # generated by the teacher (see DistillationEngine.__init__).
    "sft_sm_qft": CURRICULUM_SM_QFT,
    "sft_cosmology": CURRICULUM_COSMOLOGY,
    "sft_biochem": CURRICULUM_BIOCHEM,
    "sft_classical_condensed": CURRICULUM_CLASSICAL,
    "sft_tool_use": CURRICULUM_TOOL_USE,
}


# ═══════════════════════════════════════════════════════════════════════════
# MODEL POOL — Discovery, loading, and lifecycle management
# ═══════════════════════════════════════════════════════════════════════════
class ModelSpec:
    """Specification for a model available for distillation."""
    def __init__(self, model_id, source, path, size_gb=0, curricula=None):
        self.model_id = model_id
        self.source = source       # 'ollama' or 'gguf'
        self.path = path           # GGUF file path or Ollama model name
        self.size_gb = size_gb
        self.curricula = curricula or ["communication", "learning", "questioning", "sft_sm_qft", "sft_cosmology", "sft_biochem", "sft_classical_condensed", "sft_tool_use"]
        self.distilled = False     # True when this model is exhausted
        self.iterations = 0        # How many iterations completed
        self.stagnation_score = 0  # Rolling stagnation metric
    
    def __repr__(self):
        return f"ModelSpec({self.model_id}, src={self.source}, curricula={self.curricula})"


class ModelPool:
    """
    Discovers and manages all available models for distillation.
    """
    def __init__(self, ollama_url="http://localhost:11434", llama_server_port=8090):
        self.ollama_url = ollama_url
        self.llama_server_port = llama_server_port
        self.models = []
        self._llama_process = None
        self._active_gguf_model = None
        
    def discover_all(self):
        """Discover all models from Ollama and external SSD."""
        self.models = []
        self._discover_ollama()
        self._discover_gguf()
        distill_logger.info(
            f"ModelPool: discovered {len(self.models)} models total "
            f"({sum(1 for m in self.models if m.source == 'ollama')} ollama, "
            f"{sum(1 for m in self.models if m.source == 'gguf')} gguf)"
        )
        return self.models
    
    def _discover_ollama(self):
        """List all models available in Ollama."""
        try:
            resp = requests.get(f"{self.ollama_url}/api/tags", timeout=5)
            if resp.status_code == 200:
                models = resp.json().get("models", [])
                for m in models:
                    name = m["name"]
                    size_gb = m.get("size", 0) / (1024**3)
                    
                    # Assign curricula based on model name
                    curricula = ["communication", "learning", "questioning", "sft_sm_qft", "sft_cosmology", "sft_biochem", "sft_classical_condensed", "sft_tool_use"]
                    
                    self.models.append(ModelSpec(
                        model_id=name,
                        source="ollama",
                        path=name,
                        size_gb=size_gb,
                        curricula=curricula,
                    ))
                distill_logger.info(f"Discovered {len(models)} Ollama models.")
        except Exception as e:
            distill_logger.error(f"Ollama discovery failed: {e}")
    
    def _discover_gguf(self):
        """Scan external SSD for GGUF model files."""
        search_dirs = [_GGUF_DIR, _HIST_DIR]
        
        for base_dir in search_dirs:
            if not os.path.exists(base_dir):
                continue
            
            for entry in os.listdir(base_dir):
                full_path = os.path.join(base_dir, entry)
                
                if entry.endswith(".gguf") and os.path.isfile(full_path):
                    size_gb = os.path.getsize(full_path) / (1024**3)
                    model_id = entry.replace(".gguf", "")
                    
                    curricula = self._guess_curricula(model_id)
                    
                    self.models.append(ModelSpec(
                        model_id=f"gguf:{model_id}",
                        source="gguf",
                        path=full_path,
                        size_gb=size_gb,
                        curricula=curricula,
                    ))
                
                elif os.path.isdir(full_path):
                    # Multi-part model in a directory
                    gguf_files = [f for f in os.listdir(full_path) if f.endswith(".gguf")]
                    if gguf_files:
                        # Use the first shard
                        shard_path = os.path.join(full_path, sorted(gguf_files)[0])
                        total_size = sum(
                            os.path.getsize(os.path.join(full_path, f))
                            for f in gguf_files
                        ) / (1024**3)
                        
                        curricula = self._guess_curricula(entry)
                        
                        self.models.append(ModelSpec(
                            model_id=f"gguf:{entry}",
                            source="gguf",
                            path=shard_path,
                            size_gb=total_size,
                            curricula=curricula,
                        ))
        
        distill_logger.info(f"Discovered {sum(1 for m in self.models if m.source == 'gguf')} GGUF models.")
    
    def _guess_curricula(self, model_name):
        """Guess appropriate curricula based on model name."""
        name = model_name.lower()
        return ["communication", "learning", "questioning", "sft_sm_qft", "sft_cosmology", "sft_biochem", "sft_classical_condensed", "sft_tool_use"]
    
    def load_for_inference(self, model_spec):
        """
        Prepare a model for inference. Returns the API endpoint to use.
        
        For Ollama models: just returns the ollama URL (already loaded).
        For GGUF models: starts llama-server with the model file.
        """
        if model_spec.source == "ollama":
            return self.ollama_url, model_spec.path
        
        elif model_spec.source == "gguf":
            # Stop any previously running llama-server
            self._stop_llama_server()
            
            distill_logger.info(
                f"Starting llama-server for {model_spec.model_id} "
                f"({model_spec.size_gb:.1f} GB)..."
            )
            
            try:
                cmd = [
                    "llama-server",
                    "-m", model_spec.path,
                    "--port", str(self.llama_server_port),
                    "-ngl", "99",  # Full GPU offload on M3 Ultra
                    "-c", "4096",
                    "--no-mmap",   # Better for external SSD
                ]
                
                self._llama_process = subprocess.Popen(
                    cmd,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                self._active_gguf_model = model_spec.model_id
                
                # Wait for server to be ready
                url = f"http://localhost:{self.llama_server_port}"
                for attempt in range(60):  # Up to 60 seconds for large models
                    try:
                        r = requests.get(f"{url}/health", timeout=2)
                        if r.status_code == 200:
                            distill_logger.info(
                                f"llama-server ready for {model_spec.model_id} "
                                f"after {attempt+1}s"
                            )
                            return url, model_spec.model_id
                    except Exception:
                        pass
                    time.sleep(1)
                
                distill_logger.error(
                    f"llama-server failed to start for {model_spec.model_id}"
                )
                self._stop_llama_server()
                return None, None
                
            except Exception as e:
                distill_logger.error(f"Failed to start llama-server: {e}")
                return None, None
    
    def _stop_llama_server(self):
        """Stop any running llama-server instance."""
        if self._llama_process and self._llama_process.poll() is None:
            distill_logger.info(f"Stopping llama-server for {self._active_gguf_model}")
            self._llama_process.terminate()
            try:
                self._llama_process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self._llama_process.kill()
            self._llama_process = None
            self._active_gguf_model = None
    
    def unload_all(self):
        """Stop all running model servers."""
        self._stop_llama_server()
    
    def get_undistilled(self):
        """Return list of models not yet fully distilled."""
        return [m for m in self.models if not m.distilled]
    
    def summary(self):
        """Return a formatted summary of all models."""
        lines = ["── Model Pool ──────────────────────"]
        for m in self.models:
            status = "✓" if m.distilled else "○"
            lines.append(
                f"  {status} {m.model_id} ({m.source}, {m.size_gb:.1f}GB) "
                f"iter={m.iterations} curricula={m.curricula}"
            )
        lines.append(f"  Total: {len(self.models)} models, "
                     f"{sum(1 for m in self.models if m.distilled)} distilled")
        lines.append("────────────────────────────────────")
        return "\n".join(lines)


# ═══════════════════════════════════════════════════════════════════════════
# DISTILLATION ENGINE
# ═══════════════════════════════════════════════════════════════════════════
class DistillationEngine:
    """
    The Learning Law (paper Sec 8.3): the corpus's three-stage arc -- HOLD at the
    prediction state, CLOSE by observation, CONSOLIDATE into the held cycle.
    Grounded in constants/deposition_law.ep (Step 310: the holding store closes
    BEFORE the selecting store), constants/deposition_approach_form.ep (Step 319:
    consolidation is the fold's dyadic halving), and constants/hold_closure_regimes.ep
    (Step 312: held content re-excites, closure does not -- so the engine's OWN
    unconfirmed output is never self-reinforced; only observation-closed content
    consolidates). Cycles through teacher models, each with its own curriculum;
    detects stagnation and auto-switches; the Observer monitors quality throughout.
    """
    def __init__(self, model_pool, teacher=None, stagnation_threshold=0.7,
                 max_stagnation_streak=5, max_iters_per_seed=3):
        self.pool = model_pool
        self.stagnation_threshold = stagnation_threshold
        self.max_stagnation_streak = max_stagnation_streak
        # Per-seed iteration budget: advance to the next seed after this many
        # self-play turns even if mastery never registers, so the curriculum is
        # actually COVERED. Without this the seed only advanced on 5 consecutive
        # near-identical responses (mastery), which varied generation never
        # produces — so self-play got stuck on seed 0 forever.
        self.max_iters_per_seed = max_iters_per_seed
        self.seed_iterations = 0

        # The communication/learning/questioning curriculum is LIVE and teacher-
        # generated — nothing is hardcoded. At start we generate a FRESH batch and
        # merge it onto the persistent cache (fresh + grow + persist); during the
        # loop grow_curricula() keeps adding more.
        self.teacher = teacher
        self._grow_area_idx = 0
        self.pass_completed = False   # set True when a full curriculum pass is mastered
        # Install whatever is CACHED immediately (fast, non-blocking) so the engine
        # is usable at once. The fresh generation (a) is heavy (many blocking HTTP
        # calls) and MUST NOT run here — __init__ is called on the Discord event
        # loop, and blocking it stalls the heartbeat. refresh_all() does the fresh
        # generation, and the auto-loop runs it in a worker thread.
        try:
            self._install(load_cache())
            distill_logger.info(
                "Curriculum loaded from cache: "
                + ", ".join(f"{a}={len(CURRICULA.get(a, []))}" for a in SKILL_AREAS)
            )
        except Exception as e:
            distill_logger.error(f"Could not load cached curricula: {e}", exc_info=True)
        
        # State
        self.current_model_idx = 0
        self.current_curriculum_idx = 0
        self.current_seed_idx = 0
        self.total_iterations = 0
        
        # Stagnation detection per model
        self.recent_responses = deque(maxlen=20)
        self.stagnation_streak = 0
        
        # Progress tracking
        from omni.logging_config import LOG_DIR as _LD
        self.distill_log_path = os.path.join(_LD, "distill.jsonl")
    
    def _install(self, curricula):
        """Inject generated curricula into the global registry used by get_next_seed."""
        for area in SKILL_AREAS:
            if curricula.get(area):
                CURRICULA[area] = curricula[area]

    def refresh_all(self):
        """
        Fresh generation (a): generate a new batch for ALL skill areas, merge into
        the persistent cache, and install. BLOCKING (many HTTP calls) — callers on
        the event loop must run this via asyncio.to_thread so the heartbeat is free.
        Returns {area: new_total} or None.
        """
        if self.teacher is None:
            return None
        merged = refresh_curricula(self.teacher)
        self._install(merged)
        return {a: len(CURRICULA.get(a, [])) for a in SKILL_AREAS}

    def grow_curricula(self):
        """
        Continuous growth (b): generate a fresh batch for ONE rotating skill area,
        merge it into the persistent cache, and install it. One area per call keeps
        the pause short. Returns (area, new_total) or None.
        """
        if self.teacher is None:
            return None
        areas = list(SKILL_AREAS)
        area = areas[self._grow_area_idx % len(areas)]
        self._grow_area_idx += 1
        merged = refresh_curricula(self.teacher, areas=[area])
        self._install(merged)
        return area, len(CURRICULA.get(area, []))

    def curriculum_is_empty(self):
        """True if no teacher-generated curriculum has been installed yet."""
        return not any(CURRICULA.get(a) for a in SKILL_AREAS)

    def curriculum_counts(self):
        """{area: number of installed teacher-generated seeds}."""
        return {a: len(CURRICULA.get(a, [])) for a in SKILL_AREAS}

    def take_pass_completed(self):
        """Return True once if a full curriculum pass has completed since last checked."""
        if self.pass_completed:
            self.pass_completed = False
            return True
        return False

    def get_current_model(self):
        """Get the current model spec to distill from."""
        undistilled = self.pool.get_undistilled()
        if not undistilled:
            return None
        self.current_model_idx = self.current_model_idx % len(undistilled)
        return undistilled[self.current_model_idx]
    
    def get_next_seed(self, model_spec):
        """Get the next curriculum seed for the current model."""
        curricula_names = model_spec.curricula
        curr_name = curricula_names[self.current_curriculum_idx % len(curricula_names)]
        seeds = CURRICULA.get(curr_name) or CURRICULUM_SM_QFT   # never an empty list
        seed = seeds[self.current_seed_idx % len(seeds)]
        return seed, curr_name
    
    def advance(self, response_text):
        """
        Advance the distillation state after processing a response.

        Advances to the next seed on stagnation-mastery OR once the per-seed
        iteration budget is spent (so the curriculum is covered even when
        generation stays varied and mastery never registers as a stagnation streak).

        Returns: 'continue', 'next_seed', 'next_curriculum', 'next_model', or 'complete'
        """
        self.total_iterations += 1
        model = self.get_current_model()
        if model is None:
            self.pass_completed = True   # every model has worked through its curriculum
            return "complete"

        model.iterations += 1
        self.seed_iterations += 1

        mastered = False
        if self._check_stagnation(response_text):
            self.stagnation_streak += 1
            if self.stagnation_streak >= self.max_stagnation_streak:
                mastered = True
        else:
            self.stagnation_streak = 0

        if mastered or self.seed_iterations >= self.max_iters_per_seed:
            return self._advance_seed(model)

        return "continue"

    def _advance_seed(self, model):
        """Move to the next curriculum seed, rolling over the curriculum and then
        the model when the current one's seeds are exhausted. Resets per-seed
        state. Returns the transition: 'next_seed' | 'next_curriculum' | 'next_model'."""
        self.current_seed_idx += 1
        self.stagnation_streak = 0
        self.seed_iterations = 0
        self.recent_responses.clear()

        curricula_names = model.curricula
        curr_name = curricula_names[self.current_curriculum_idx % len(curricula_names)]
        seeds = CURRICULA.get(curr_name, CURRICULUM_SM_QFT)

        if self.current_seed_idx >= len(seeds):
            self.current_curriculum_idx += 1
            self.current_seed_idx = 0
            if self.current_curriculum_idx >= len(curricula_names):
                model.distilled = True
                self.current_model_idx += 1
                self.current_curriculum_idx = 0
                self.pass_completed = True   # this model finished its whole curriculum
                return "next_model"
            return "next_curriculum"
        return "next_seed"
    
    def _check_stagnation(self, response_text):
        """Check if the latest response is too similar to recent ones."""
        # Use word sets for similarity to avoid positional/shifting brittleness
        words = set(response_text.lower().split())
        
        if len(self.recent_responses) < 5:
            self.recent_responses.append(words)
            return False
        
        # Check semantic/word-level overlap with recent responses
        overlap_count = 0
        for prev_words in self.recent_responses:
            if not prev_words or not words:
                continue
                
            intersection = len(words.intersection(prev_words))
            union = len(words.union(prev_words))
            ratio = intersection / union if union > 0 else 0
            
            if ratio > self.stagnation_threshold:
                overlap_count += 1
        
        self.recent_responses.append(words)
        
        # Stagnant if >50% of recent responses are >70% similar
        return overlap_count > len(self.recent_responses) * 0.5
    
    def query_model(self, api_url, model_name, prompt, system=None, temperature=0.9,
                    top_p=0.95, repeat_penalty=1.2):
        """
        Query a model via Ollama or llama-server compatible API.
        
        Returns the response text.
        """
        try:
            if "localhost:11434" in api_url:
                # Ollama API
                resp = requests.post(
                    f"{api_url}/api/generate",
                    json={
                        "model": model_name,
                        "prompt": prompt,
                        "system": system if system else "",
                        "stream": False,
                        "options": {
                            "num_predict": 8192,
                            "temperature": temperature,
                            "top_p": top_p,
                            "repeat_penalty": repeat_penalty,
                            "num_ctx": detect_context_window(model_name, api_url)  # provider-reported full window
                        },
                    },
                    timeout=120,
                )
                if resp.status_code == 200:
                    return resp.json().get("response", "")
            else:
                # llama-server API (OpenAI-compatible)
                resp = requests.post(
                    f"{api_url}/v1/completions",
                    json={
                        "prompt": prompt,
                        "max_tokens": 8192,
                        "temperature": temperature,
                        "top_p": top_p,
                        "repeat_penalty": repeat_penalty,
                    },
                    timeout=120,
                )
                if resp.status_code == 200:
                    choices = resp.json().get("choices", [])
                    if choices:
                        return choices[0].get("text", "")
            
            return ""
            
        except Exception as e:
            distill_logger.error(f"Query failed: {e}")
            return ""
    
    def log_iteration(self, model_id, curriculum, seed, response, 
                      self_rating=None, teacher_rating=None, observer_note=None):
        """Log a distillation iteration to the JSONL log."""
        import datetime
        record = {
            "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
            "iteration": self.total_iterations,
            "model": model_id,
            "curriculum": curriculum,
            "seed": seed,
            "response_length": len(response),
            "response_preview": response[:200],
            "self_rating": self_rating,
            "teacher_rating": teacher_rating,
            "observer_note": observer_note,
        }
        try:
            with open(self.distill_log_path, "a") as f:
                f.write(json.dumps(record) + "\n")
        except Exception:
            distill_logger.error("Failed to write distill log", exc_info=True)
    
    def status(self):
        """Return a status summary."""
        model = self.get_current_model()
        model_name = model.model_id if model else "COMPLETE"
        undistilled = len(self.pool.get_undistilled())
        total = len(self.pool.models)
        
        return {
            "total_iterations": self.total_iterations,
            "current_model": model_name,
            "models_remaining": undistilled,
            "models_total": total,
            "current_curriculum_idx": self.current_curriculum_idx,
            "current_seed_idx": self.current_seed_idx,
            "stagnation_streak": self.stagnation_streak,
        }
